# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    ../modules/audio/audio.nix
  ];


  # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.useOSProber = true;

  # SEE: https://nixos.wiki/wiki/Libvirt
  boot.extraModprobeConfig = "options kvm_intel nested=1";

  boot.kernel.sysctl = {
    "net.ipv4.ip_unprivileged_port_start" = 80;
  };

  networking.hostName = "work-1"; # Define your hostname.


  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ config.boot.kernelPackages.sysdig ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/62080bc0-34dc-4da9-810c-a6260a9e2a79";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/a09d5862-535f-416a-824a-6a1c713ff3d5"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens33.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  environment.systemPackages = with pkgs; [
    microsoft-edge
    # xrdp
  ];

  # networking.firewall.allowedTCPPorts = [
  #   3389
  # ];
  # networking.firewall.allowedUDPPorts = [
  #   3389
  # ];
  # services.xrdp = {
  #   enable = true;
  #   openFirewall = true;
  # };

}
